export enum Status {
    SUCCESS,
    CREATED,
    FAILED_VALIDATION,
    CONFLICT,
    NOT_FOUND,
    ERROR,
    PRECONDITION_FAILED,
    SUCCESS_NO_CONTENT,
    FORBIDDEN,
    UNPROCESSABLE_ENTRY,
    UNAUTHORIZED,
}